server:
  port: 6060
spring:
  #出现错误时, 直接抛出异常(便于异常统一处理，否则捕获不到404)
  mvc:
    throw-exception-if-no-handler-found: true
app:
  #sToken: QDG6eK
  #sCorpID: wx5823bf96d3bd56c7
  #sEncodingAESKey: jWmYm7qr5nMoAUwZRjGtBxmz3KA1tkAj3ykkR6q2B2C
  sToken: zZVNkOD1iVl
  sCorpID: wwded2338038363bc0
  sEncodingAESKey: m2AziCkKT5eWTouyl5k9dOpqIDbx87t57KXV1OXjooR